paths:
  /api/getcsrftoken/:            
    get:                 
      summary: Use to request a csrf token
      produces:
      - application/json
      responses:
        '200':
          description: A successful response
          content:
            application/json:
              schema:
                $ref: '#/definitions/apiResponse'
  
  /api/http/{method}:
    post:
      summary: Make request and examine specified url
    parameters:      
      - in: body       
        description: set url to examine
        required: true
        schema:          
          $ref: '#/definitions/callRequest' 
      - name: method
        in: path
        description: HTTP verb to perform action
        required: true,
        schema:
          type: string
          enum: 
            - GET
            - POST
            - PUT
            - DELETE
    responses:
      '200':
        description: Successfully created user
        content:
            application/json:
              schema:
                $ref: '#/definitions/apiResponse'
      '403': 
        description: Missing CSRF token
  
  /api/{id}:
    get:
      suumary: Get previouly saved data
    parameters:
      - name: id
        in: path
        description: Id of shared content
        required: true
        schema:
          type: string
          format: string
    responses:
      '200':
        description: Successful response
        content: 
          application/json:
            schema:
              type: array
              items:
                $ref: '#/definitions/callResponse'
                
      '404':
        description: Data not found
      '403':
        description: Missing CSRF token


definitions:  
  apiResponse:
    type: object
    properties:
      errors:
        type: string
        description: Error description
      status:
        type: integer
        description: http status code
      data:
        type: object
        description: Response data
  callRequest:
    type: object
    properties:
      url:
        type: string
        description: URL to examine
  callResponse:
    type: object
    properties:
      errors:
        type: string
        description: Error description
        example: An error ocurred while perform action
      status:
        type: integer
        description: http status code
        example: 200
      data:        
        properties: 
          url:
            type: object
            properties: 
              domain:
                type: string
                example: www.google.com
              scheme:
                type: string
                example: http
              path:
                type: string
                example: /
          request:
            type: object
            properties:
              id: 
                type: string
                summary: Shared id
          response:
            type: array
            items:
            oneOf:
              - $ref: '#/definitions/Response'
  Response:
    type: object
    properties:
      location:
        type: string
        example: /
      server:
        type: string               
      date:
        type: date
        example: 2021-09-15T10:32:09.157Z
      statusCode:
        type: integer
        example: 200       
      http:
        type: string
        example: HTTP 1.1         
